### ISSUE TITLE
First word cannot be highlighted if any large log file output is much faster than working of txtstyle

### ISSUE THREAD

**Issue by Zesko** [armandino/TxtStyle#5]
My config of Java:
```
[Style="java"]
white on-green bold: regex("INFO")
```
There is the large log file in docker container.

When I run `docker logs <container name > -f | txts -n java`

Every first word "INFO" was not highlighted in some lines, but rest other lines are highlighted when "INFO" is not first word.

**Because the output of Docker log is much faster than working of txtstyle.**

![image](https://user-images.githubusercontent.com/17826352/177350321-7278de50-4ef7-4621-8332-dd1253ff48be.png)
```
...
INFO: No context init parameter 'facelets.REFRESH_PERIOD' found, using default value '-1'.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
INFO: No context init parameter 'javax.faces.FACELETS_RESOURCE_RESOLVER' found.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
INFO: No context init parameter 'facelets.RESOURCE_RESOLVER' found.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
INFO: No context init parameter 'org.apache.myfaces.MARK_INITIAL_STATE_WHEN_APPLY_BUILD_VIEW' found, using default value 'false'.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
INFO: No context init parameter 'facelets.DECORATORS' found.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
INFO: No context init parameter 'facelets.SKIP_COMMENTS' found.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
INFO: No context init parameter 'org.apache.myfaces.WRAP_TAG_EXCEPTIONS_AS_CONTEXT_AWARE' found, using default value 'true'.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
INFO: No context init parameter 'org.apache.myfaces.CACHE_EL_EXPRESSIONS' found, using default value 'noCache'.
Jul 05, 2022 2:14:05 PM org.apache.myfaces.webapp.WebConfigParamsLogger logWebContextParams
...
```
When I run `cat  <log.file> | txts -n java`, that is the same as the log, but that works fine.

**Comment by armandino** [comment]
@Zesko thanks for reporting this. Could you please attach your `.txts.conf` and the log file so that I can reproduce this locally?

**Comment by Zesko** [comment]
The config file `.txts.conf`: 
```
[Style="java"]
!red: regex("Exception")
red bold: regex("error")
white on-red bold: regex("ERROR")
white on-129 bold: regex("WARN")
white on-blue bold: regex("DEBUG")
white on-green bold: regex("INFO")
green bold: regex("\(\w+\.java:\d+\)")
grey : regex("\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d(,\d\d\d)?")
yellow: regex("[a-zA-Z]+:\d+")
yellow: regex("com\.[\w+|\.]+")
cyan: regex("org\.[\w+|\.]+")
blue: regex("\[[^\]]+\]")
```
If this issue appears with this config, then I changed the config file:

```
[Style="java"]
white on-green bold: regex("INFO")
```

It has the same issue again.

**Comment by Zesko** [comment]
>  the log file so that I can reproduce this locally?

The issue is dependent on speed of output from Docker log.

**Comment by Zesko** [comment]
My suggested solution:

A recorder is to be implemented to quickly capture any large text from any output and stores it in a buffer.
The TxtStyle process fetches part of this text from the buffer and processes ... when done then it fetches other part of this text ....

**Comment by Zesko** [comment]
I notice that another problem: 
Some parts of text are in the wrong order when output of Docker log is very fast.

**Comment by Zesko** [comment]
`grep` has the same issue with speed of Docker log

Solution to add: `2>&1`.

 https://stackoverflow.com/questions/34724980/finding-a-string-in-docker-logs-of-container

Change

```
docker logs <container name>  -f | txts -n java
```
to
```
docker logs <container name> -f 2>&1 | txts -n java
```
That works like a charm!

![Screenshot_20220705_193748](https://user-images.githubusercontent.com/17826352/177384777-2d96ec46-ba0d-42db-95ef-72c2dc8bd43d.png)

**Comment by Zesko** [comment]
There is a explanation about `2>&1` https://stackoverflow.com/questions/818255/in-the-shell-what-does-21-mean

The problem has nothing to do with TxtStyle. Sorry for my misunderstanding
I closed this issue now.

**Comment by armandino** [comment]
@Zesko thank you for the update. Just to confirm, redirecting `stderr` to `stdout` using `2>&1` resolved the first problem, where some matches were not highlighted.

Are you still seeing the second issue where text is output in the wrong order?

**Comment by Zesko** [comment]
> Are you still seeing the second issue where text is output in the wrong order?

Using 2>&1 resolved the second problem too.

**Comment by Zesko** [comment]
You can write the redirecting `2>&1` in ReadMe, thanks!

**Comment by armandino** [comment]
Great, thank you for providing all the details. Much appreciated!
